version: "3.9"

services:
  php:
    container_name: php
    image: php
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/var/www/html
      - ./log/apache2:/var/log/apache2
      - ./log/cron:/var/log/cron
      - ./cron:/etc/cron.d/cron
    ports:
      - "${PORT}:80"